name: CI Tests
on: [push, pull_request]

jobs:
    PHPUnit:
        runs-on: $${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest]
                php:
                    - 7.0
                    - 7.1
                    - 7.2
                    - 7.3
                    - 7.4
                    - 8.0
                    - 8.0
                include:
                    - os: precise
                      php: 5.4
                    - os: trusty
                      php: 5.5
                    - os: trusty
                      php: 5.6
        steps:
            - uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: $${{ matrix.php }}

            - name: Install dependencies
              run: composer install

            - name: Run PHPUnit
              if: ${{ !cancelled() }}
              run: vendor/bin/phpunit
